GET http://localhost:4000/users

###

GET http://localhost:4000/users/3

###

POST http://localhost:4000/users
Content-Type: application/json

{
    "firstname": "UserThreeButIdSix",
    "lastname": "Exists",
    "email": "someMMoreEmail",
    "password": "345"
}

###

POST http://localhost:4000/createUser
Content-Type: application/json

###

DELETE  http://localhost:4000/users/3

###

PATCH   http://localhost:4000/users/4
Content-Type: application/json

{
    "firstname": "UserOneButIdFour"
}

###














POST    http://localhost:4000/login
Content-Type: application/json

{
    "email": "nafan9-roma@mail.ru",
    "password": "99145673"
}

###

POST    http://localhost:4000/register
Content-Type: application/json

{
    "firstname": "UserCreatedByFuncNumFour",
    "lastname": "Exists",
    "email": "NewEmail",
    "password": "333"
}

###

GET http://localhost:4000/users/1

###

GET http://localhost:4000/profile/5

###

PATCH   http://localhost:4000/profile/5
Content-Type: application/json

{
    "status": "NOTAAO"

}


###

PATCH   http://localhost:4000/profile/5/links
Content-Type: application/json

{
  "twitter": "ANDMAYBEYES"

}


###

PATCH   http://localhost:4000/profile/2/follow/5


###

DELETE   http://localhost:4000/profile/5/unfollow/6

###

POST http://localhost:4000/profile/5/createPost
Content-Type: application/json

{
    "text": "pizda"
}

###

DELETE http://localhost:4000/profile/5/deletePost/6

###

PATCH http://localhost:4000/profile/5/posts/8
Content-Type: application/json

{
    "text": "EZ"
}

###

GET http://localhost:4000/posts/3/1

###

GET http://localhost:4000/profile/5/posts/3/1

###

GET http://localhost:4000/profile/5/posts/15